### ISSUE TITLE
Sonarr V4: Passwords and API keys are obfuscated

### ISSUE THREAD

**Issue by Callum027** [buildarr/buildarr-sonarr#34]
Sonarr V4 introduced a change where any passwords or API keys returned via the API (and to the UI) are obfuscated with `*` characters.

This makes it impossible to idempotently check and update resources with API keys or passwords in them.

I have created an issue upstream, to see if a solution to this issue can be reached.

Upstream issue: https://github.com/Sonarr/Sonarr/issues/6169

**Comment by Callum027** [comment]
Upstream has decided on not providing a way to detect if a password was actually changed or not, but ensuring that notification connections, and other resources, are not re-tested if no parameters have changed.

This is not ideal, but I can rework the password handling to hopefully reduce the impact of this.

**Comment by jvrobert** [comment]
Hi is there a workaround for this? I can't get prowlarr to add Sonarr as an app at all now, no matter what I do it seems to try to pull the API key from sonarr:
pydantic.error_wrappers.ValidationError: 1 validation error for SonarrApplication
api_key
  ensure this value has at least 32 characters (type=value_error.any_str.min_length; limit_value=32)

I have this, no instance link or anything
```
      applications:
        definitions:
          sonarr-anime-prowlarr:
            type: "sonarr"
            api_key: 1234570ac62b4daa123457eaec7365b5
            prowlarr_url: "https://prowlarr.my.net"
            base_url: "https://sonarr-anime.my.net/"
            sync_anime_standard_format_search: true
            sync_level: "full-sync"
            sync_categories:
              - "TV/Anime"
            tags:
              - "anime"
```
